"""
This config file contains the information specific to the individual usage of ask-a-tech.

Please rename this file to
"config.py" and add or replace the information with your own.
"""
__author__ = 'ericpoe'
__date__ = '2014-01-21'

## Google Apps Connection Information
# The user email/password defined should have edit-rights to the appropriate spreadsheet in Google Drive
gapps = {}  # DO NOT CHANGE THIS LINE
gapps['email'] = ''  # eg. 'user@example.com'
gapps['password'] = ''
gapps['project_name'] = 'Ask-A-Tech'

## Google Spreadsheet Information
# The spreadsheet's key is found in the URL for the spreadsheet between the "key=" and the "&".
# The sheet's "sheet" and "archive" IDs should not change. However, if they do, they can be found in the output for
# 'feed = gd_client.GetWorksheetsFeed(config.sheet['key'])'
sheet = {}  # DO NOT CHANGE THIS LINE
sheet['key'] = ''
sheet['sheet'] = 'od6'
sheet['archive'] = 'od7'

## Web Help Desk Information
# The apikey is generated by a tech in WHD by following the instructions at http://www.webhelpdesk.com/api/#auth
#
# The easiest way to figure out the JSON data is create a bogus ticket within WHD that has the problem type,
# location, status, and priority that you want all of your Ask-A-Tech tickets to have in common. Once that ticket is
# created, grab the JSON generated from following http://www.webhelpdesk.com/api/#tickets-detail
whd = {}  # DO NOT CHANGE THIS LINE
whd['apikey'] = ''
whd['host'] = ''  # eg. 'helpdesk.example.com'
whd['json'] = {}  # DO NOT CHANGE THIS LINE
whd['json']['ProblemType'] = 0  # eg. 42
whd['json']['Location'] = 0  # eg. 17
whd['json']['StatusType'] = 0  # eg. 1
whd['json']['PriorityType'] = 0  # eg. 1